subdir-ccflags-y += -Werror
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek
# In case the platform does NOT support this type of sensors

ifneq ($(CONFIG_TOUCHSCREEN_MTK),)
obj-y   +=  mtk_tpd.o tpd_button.o tpd_calibrate.o tpd_debug.o \
		tpd_default.o tpd_init.o tpd_misc.o tpd_setting.o
endif

obj-$(CONFIG_TOUCHSCREEN_MTK)   += tpd_common_probe.o

#obj-$(CONFIG_TOUCHSCREEN_MTK)	+=  GT1151/
obj-$(CONFIG_TOUCHSCREEN_MTK_NT36xxx)	+=  aeon_nt36xxx/
obj-$(CONFIG_TOUCHSCREEN_MTK_SSL_SSD20XX)	+=  SSD209XX/